# Generated by Django 5.2.8 on 2025-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
