# Generated by Django 5.2.8 on 2025-11-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='formato_venta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio Venta'),
        ),
    ]
