# Generated by Django 5.2.8 on 2025-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('trabajador', 'Trabajador')], default='trabajador', max_length=50),
        ),
    ]
